#########################################################################
#      Copyright (C) 2025        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################

---

AWSTemplateFormatVersion: "2010-09-09"

Description: This template creates a new VPC and deploys a HA cluster in AWS

#============================================================
# UI Definition
#============================================================
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Cluster Master Configuration
        Parameters:
          - InstanceMasterImageId
          - InstanceMasterInstanceType
      -
        Label:
          default: Cluster Worker Configuration
        Parameters:
          - InstanceWorkerImageId
          - InstanceWorkerInstanceType
      -
        Label:
          default: Network Configuration
        Parameters:
          - HostedZoneName
          - PrivateIpAddressInstanceMaster0
          - PrivateIpAddressInstanceWorker0
          - SecurityGroupCidrIp
          - SubnetCidrBlockPublic
          - VPCCidrBlock
      -
        Label:
          default: Security Configuration
        Parameters:
          - KeyPair0PublicKeyMaterial         
          
    ParameterLabels:
      HostedZoneName:
        default: The name of the hosted zone that you want to create records in
      InstanceMasterImageId:
        default: AMI to use for Cluster Master Instances
      InstanceMasterInstanceType:
        default: Cluster Master Instance Size
      InstanceWorkerImageId:
        default: AMI to use for Cluster Worker Instances
      InstanceWorkerInstanceType:
        default: Cluster Worker Instance Size
      KeyPair0PublicKeyMaterial:
        default: Public SSH key for group 0 instances
      PrivateIpAddressInstanceMaster0:
        default: The private IP address for Master 0
      PrivateIpAddressInstanceWorker0:
        default: The private IP address for Worker 0
      SecurityGroupCidrIp:
        default: Allowed CIDR for SSH EC2 instance Access
      SubnetCidrBlockPublic:
        default: Public Subnet CIDR
      VPCCidrBlock:
        default: VPC CIDR
                
Parameters:

  HostedZoneName:
    Default: 'sebastian-colomar.es'
    Description: >
      The name of the hosted zone that you want to create records in.
    Type: String

  InstanceMasterImageId:
    Default: ami-02d26659fd82cf299 #MUMBAI #UBUNTU24
    Description: >
      Select AMI to use for the Cluster Master instances. 
      When it's left blank, the default AMI for your AWS region will be used. 
      When setting an AMI, it must be available in your current region.
    Type: String
    
  InstanceMasterInstanceType:
    Default: 't3a.small'
    Description: >
      Select Amazon EC2 instance type for the Cluster Master instances.
    Type: String
    
  InstanceWorkerImageId:
    Default: ami-02d26659fd82cf299 #MUMBAI #UBUNTU24
    Description: >
      Select AMI to use for the Cluster Worker instances. 
      When it's left blank, the default AMI for your AWS region will be used. 
      When setting an AMI, it must be available in your current region.
    Type: String
    
  InstanceWorkerInstanceType:
    Default: 't3a.micro'
    Description: >
      Select Amazon EC2 instance type for the Cluster Worker instances.
    Type: String

  KeyPair0PublicKeyMaterial:
    Default: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQD+jz+hUdltY1wBrLs5D0Or6xaLBvTbfa/933B8IxKueX+Vh6GiBbF7xqag7UkBjgCCkG07dIzWRgodtR8worBxz81FL3r+ye60arOVMp3PIQo6LNIJrc4xrFghhzIQKLDDWgQZb3kiHkIBwBL74ez+q7UUSn3Bcyl8UWT3RxsSY968AD284Vld2Dz2i6tyR46CchuQASsswrPCE4y6t/5nJYOJniPGATICVenPAg6SPqXqFNkbDdsVGe0U3deTZvtBubB/tsoKzddZgqC8RkYcOTo07paqUq0Dui0AJDp6V90ziyaVdvG/WWUGjEL9fxJ5HNq5lXObU2fbegcNqhThn+U1r857AlmjyGcowTNZYfSN7Woh4mGHpPfmetfBnj/KWodiomTH1zzrS5lrFxlWPwzJYtcXyU5WOUYiIkRKzC0EgF3H8m2vvvCpaZItww0C7X7DTKnrOBYry67nvi8UgSSE2kHI8BzaqKX78BufAOGjeVhyqLMRammFNP8ILCE=
    Description: >
      Public SSH key used to access the group 0 instances.
    Type: String
    
  PrivateIpAddressInstanceMaster0:
    Default: 10.168.2.100
    Description: >
      The private IP address for Master 0.
    Type: String

  PrivateIpAddressInstanceWorker0:
    Default: 10.168.2.200
    Description: >
      The private IP address for Worker 0.
    Type: String
    
  SecurityGroupCidrIp:
    Default: 0.0.0.0/0
    Description: >
      Allowed CIDR block for external SSH access to the EC2 instances. 
      It defines the block of IPs that can access the EC2 instances. 
      Set it to 0.0.0.0/0 to make it accessible from anywhere.
    Type: String
    
  SubnetCidrBlockPublic:
    Default: 10.168.2.0/24
    Description: >
      CIDR block for public (DMZ) subnet located in Availability Zone 1. 
      All resources located on this subnet are provided an IP within this address block. 
    Type: String
    
  VPCCidrBlock:
    Default: 10.168.0.0/16
    Description: >
      CIDR block for the VPC. All the subnets and resources will have an IP within this address block.
    Type: String
    
#============================================================
# Resources
#============================================================
Resources:

  EIPMaster0:
    Properties:
      Domain: vpc
      InstanceId: !Ref InstanceMaster0
    Type: AWS::EC2::EIP

  EIPWorker0:
    Properties:
      Domain: vpc
      InstanceId: !Ref InstanceWorker0
    Type: AWS::EC2::EIP

  InstanceMaster0:
    Properties:
      IamInstanceProfile: !Ref InstanceProfile
      ImageId: !Ref InstanceMasterImageId
      InstanceType: !Ref InstanceMasterInstanceType
      KeyName: KeyPair0
      PrivateIpAddress: !Ref PrivateIpAddressInstanceMaster0
      SecurityGroupIds:
        - !GetAtt VPC.DefaultSecurityGroup
        - !Ref SecurityGroup
      SubnetId: !Ref SubnetPublic
      UserData:
      Fn::Base64: !Sub |
        #cloud-config
        preserve_hostname: false
        manage_etc_hosts: true
        fqdn: master0.${HostedZoneName}
      Tags:
        - Key: Name
          Value: !Sub "master0.${HostedZoneName}"
    Type: AWS::EC2::Instance
            
  InstanceProfile:
    Properties:
      Roles: [!Ref Role]
    Type: AWS::IAM::InstanceProfile

  InstanceWorker0:
    DependsOn: [VPCGatewayAttachment]  
    Properties:
      IamInstanceProfile: !Ref InstanceProfile
      ImageId: !Ref InstanceWorkerImageId
      InstanceType: !Ref InstanceWorkerInstanceType
      KeyName: KeyPair0
      PrivateIpAddress: !Ref PrivateIpAddressInstanceWorker0
      SecurityGroupIds:
        - !GetAtt VPC.DefaultSecurityGroup
        - !Ref SecurityGroup
      SubnetId: !Ref SubnetPublic
      UserData:
      Fn::Base64: !Sub |
        #cloud-config
        preserve_hostname: false
        manage_etc_hosts: true
        fqdn: worker0.${HostedZoneName}
      Tags:
        - Key: Name
          Value: !Sub "worker0.${HostedZoneName}"
    Type: AWS::EC2::Instance

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  KeyPair0:
    Properties:
      KeyName: KeyPair0
      PublicKeyMaterial: !Ref KeyPair0PublicKeyMaterial
    Type: AWS::EC2::KeyPair

  RecordSetMaster0:
    DependsOn: [EIPMaster0]
    Properties: 
      HostedZoneName: !Sub '${HostedZoneName}.'
      Name: !Sub 'master0.${HostedZoneName}'
      ResourceRecords:
        - !Ref EIPMaster0
      TTL: 60
      Type: A
    Type: AWS::Route53::RecordSet

  RecordSetWorker0:
    DependsOn: [EIPWorker0]
    Properties: 
      HostedZoneName: !Sub '${HostedZoneName}.'
      Name: !Sub 'worker0.${HostedZoneName}'
      ResourceRecords:
        - !Ref EIPWorker0
      TTL: 60
      Type: A
    Type: AWS::Route53::RecordSet

  Role:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          -
            Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    Type: AWS::IAM::Role

  RoutePublic:
    DependsOn: [VPCGatewayAttachment]
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref RouteTablePublic
    Type: AWS::EC2::Route

  RouteTablePublic:
    Properties:
      VpcId: !Ref VPC
    Type: AWS::EC2::RouteTable

  SecurityGroup:
    Properties:
      GroupDescription: Security Group to access via SSH the EC2 Instances
      SecurityGroupIngress: 
        - 
          CidrIp: !Ref SecurityGroupCidrIp
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22        
      VpcId: !Ref VPC
    Type: AWS::EC2::SecurityGroup

  SubnetPublic:
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: !Ref 'AWS::Region'
      CidrBlock: !Ref SubnetCidrBlockPublic
      VpcId: !Ref VPC
    Type: AWS::EC2::Subnet

  SubnetRouteTableAssociationPublic:
    Properties:
      RouteTableId: !Ref RouteTablePublic
      SubnetId: !Ref SubnetPublic
    Type: AWS::EC2::SubnetRouteTableAssociation

  VPC:
    Properties:
      CidrBlock: !Ref VPCCidrBlock
    Type: "AWS::EC2::VPC"

  VPCGatewayAttachment:
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
    Type: AWS::EC2::VPCGatewayAttachment
