#########################################################################
#      Copyright (C) 2025        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################

---

AWSTemplateFormatVersion: "2010-09-09"

Description: This template creates a new VPC and deploys a HA cluster in AWS

#============================================================
# UI Definition
#============================================================
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Cluster Master Configuration
        Parameters:
          - InstanceMasterImageId
          - InstanceMasterInstanceType
          - InstanceMasterVolumeSize
      -
        Label:
          default: Cluster Worker Configuration
        Parameters:
          - InstanceWorkerImageId
          - InstanceWorkerInstanceType
          - InstanceWorkerVolumeSize
      -
        Label:
          default: Network Configuration
        Parameters:
          - HostedZoneName
          - PrivateIpPrefixInstanceMaster
          - PrivateIpPrefixInstanceWorker
          - SecurityGroupCidrIp
          - SubnetCidrBlockPublic
          - VPCCidrBlock
      -
        Label:
          default: Security Configuration
        Parameters:
          - KeyPairPublicKeyMaterial         
          - KeyPairSecondaryPublicKeyMaterial         
          
    ParameterLabels:
      HostedZoneName:
        default: The name of the hosted zone that you want to create records in
      InstanceMasterImageId:
        default: AMI to use for Cluster Master Instances
      InstanceMasterInstanceType:
        default: Cluster Master Instance Size
      InstanceMasterVolumeSize:
        default: Cluster Master Volume Size
      InstanceWorkerImageId:
        default: AMI to use for Cluster Worker Instances
      InstanceWorkerInstanceType:
        default: Cluster Worker Instance Size
      InstanceWorkerVolumeSize:
        default: Cluster Worker Volume Size
      KeyPairPublicKeyMaterial:
        default: Public SSH main key for instances
      KeyPairSecondaryPublicKeyMaterial:
        default: Public SSH secondary key for instances
      PrivateIpPrefixInstanceMaster:
        default: The private IP network prefix for Master instances
      PrivateIpPrefixInstanceWorker:
        default: The private IP network prefix for Worker instances
      SecurityGroupCidrIp:
        default: Allowed CIDR for SSH EC2 instance Access
      SubnetCidrBlockPublic:
        default: Public Subnet CIDR
      VPCCidrBlock:
        default: VPC CIDR
                
Parameters:

  HostedZoneName:
    Default: 'sebastian-colomar.es'
    Description: >
      The name of the hosted zone that you want to create records in.
    Type: String

  Indices:
    Default: '00,01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16,17,18,19,20,21,22'
    Type: CommaDelimitedList

  InstanceMasterImageId:
    Default: ami-02b8269d5e85954ef #MUMBAI #UBUNTU24
    Description: >
      Select AMI to use for the Cluster Master instances. 
      When it's left blank, the default AMI for your AWS region will be used. 
      When setting an AMI, it must be available in your current region.
    Type: String
    
  InstanceMasterInstanceType:
    Default: 't3a.small'
    Description: >
      Select Amazon EC2 instance type for the Cluster Master instances.
    Type: String
 
  InstanceMasterVolumeSize:
    Default: 20
    Description: >
      Select Amazon EC2 volume size for the Cluster Master instances.
    Type: Number

  InstanceWorkerImageId:
    Default: ami-02b8269d5e85954ef #MUMBAI #UBUNTU24
    Description: >
      Select AMI to use for the Cluster Worker instances. 
      When it's left blank, the default AMI for your AWS region will be used. 
      When setting an AMI, it must be available in your current region.
    Type: String
    
  InstanceWorkerInstanceType:
    Default: 't3a.small'
    Description: >
      Select Amazon EC2 instance type for the Cluster Worker instances.
    Type: String

  InstanceWorkerVolumeSize:
    Default: 20
    Description: >
      Select Amazon EC2 volume size for the Cluster Worker instances.
    Type: Number

  KeyPairPublicKeyMaterial:
    Default: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQD+jz+hUdltY1wBrLs5D0Or6xaLBvTbfa/933B8IxKueX+Vh6GiBbF7xqag7UkBjgCCkG07dIzWRgodtR8worBxz81FL3r+ye60arOVMp3PIQo6LNIJrc4xrFghhzIQKLDDWgQZb3kiHkIBwBL74ez+q7UUSn3Bcyl8UWT3RxsSY968AD284Vld2Dz2i6tyR46CchuQASsswrPCE4y6t/5nJYOJniPGATICVenPAg6SPqXqFNkbDdsVGe0U3deTZvtBubB/tsoKzddZgqC8RkYcOTo07paqUq0Dui0AJDp6V90ziyaVdvG/WWUGjEL9fxJ5HNq5lXObU2fbegcNqhThn+U1r857AlmjyGcowTNZYfSN7Woh4mGHpPfmetfBnj/KWodiomTH1zzrS5lrFxlWPwzJYtcXyU5WOUYiIkRKzC0EgF3H8m2vvvCpaZItww0C7X7DTKnrOBYry67nvi8UgSSE2kHI8BzaqKX78BufAOGjeVhyqLMRammFNP8ILCE=
    Description: >
      Public SSH key used to access the instances.
    Type: String

  PrivateIpPrefixInstanceMaster:
    Default: 10.168.2.1
    Description: >
      The private IP network prefix for Master instances.
    Type: String

  PrivateIpPrefixInstanceWorker:
    Default: 10.168.2.2
    Description: >
      The private IP network prefix for Worker instances.
    Type: String

  SecurityGroupCidrIp:
    Default: 0.0.0.0/0
    Description: >
      Allowed CIDR block for external SSH access to the EC2 instances. 
      It defines the block of IPs that can access the EC2 instances. 
      Set it to 0.0.0.0/0 to make it accessible from anywhere.
    Type: String
    
  SubnetCidrBlockPublic:
    Default: 10.168.2.0/24
    Description: >
      CIDR block for public (DMZ) subnet located in Availability Zone 1. 
      All resources located on this subnet are provided an IP within this address block. 
    Type: String
    
  VPCCidrBlock:
    Default: 10.168.0.0/16
    Description: >
      CIDR block for the VPC. All the subnets and resources will have an IP within this address block.
    Type: String
    
#============================================================
# Resources
#============================================================
Resources:

  Fn::ForEach::Indices:
    - Index
    - !Ref Indices
    - 
      EIPMaster${Index}:
        Properties:
          Domain: vpc
          InstanceId: !Ref
            Fn::Sub: InstanceMaster${Index}
        Type: AWS::EC2::EIP

      EIPWorker${Index}:
        Properties:
          Domain: vpc
          InstanceId: !Ref
            Fn::Sub: InstanceWorker${Index}
        Type: AWS::EC2::EIP

      InstanceMaster${Index}:
        Properties:
          BlockDeviceMappings:
            - DeviceName: /dev/sda1
              Ebs:
                VolumeSize: !Ref InstanceMasterVolumeSize        
          IamInstanceProfile: !Ref InstanceProfile
          ImageId: !Ref InstanceMasterImageId
          InstanceType: !Ref InstanceMasterInstanceType
          KeyName: !Ref KeyPair
          PrivateIpAddress: !Sub ${PrivateIpPrefixInstanceMaster}${Index}
          SecurityGroupIds:
            - !GetAtt VPC.DefaultSecurityGroup
            - !Ref SecurityGroup
          SubnetId: !Ref SubnetPublic
          Tags:
            - Key: Name
              Value: !Sub master${Index}.${HostedZoneName}
        Type: AWS::EC2::Instance

      InstanceWorker${Index}:
        DependsOn: [VPCGatewayAttachment]  
        Properties:
          BlockDeviceMappings:
            - DeviceName: /dev/sda1
              Ebs:
                VolumeSize: !Ref InstanceWorkerVolumeSize        
          IamInstanceProfile: !Ref InstanceProfile
          ImageId: !Ref InstanceWorkerImageId
          InstanceType: !Ref InstanceWorkerInstanceType
          KeyName: !Ref KeyPair
          PrivateIpAddress: !Sub ${PrivateIpPrefixInstanceWorker}${Index}
          SecurityGroupIds:
            - !GetAtt VPC.DefaultSecurityGroup
            - !Ref SecurityGroup
          SubnetId: !Ref SubnetPublic
          Tags:
            - Key: Name
              Value: !Sub worker${Index}.${HostedZoneName}
        Type: AWS::EC2::Instance

      RecordSetMaster${Index}:
        DependsOn:
          - !Sub EIPMaster${Index}
        Properties: 
          HostedZoneName: !Sub ${HostedZoneName}.
          Name: !Sub master${Index}.${HostedZoneName}
          ResourceRecords:
            - !Ref
                Fn::Sub: EIPMaster${Index}
          TTL: 300
          Type: A
        Type: AWS::Route53::RecordSet

      RecordSetWorker${Index}:
        DependsOn:
          - !Sub EIPWorker${Index}
        Properties: 
          HostedZoneName: !Sub ${HostedZoneName}.
          Name: !Sub worker${Index}.${HostedZoneName}
          ResourceRecords:
            - !Ref 
                Fn::Sub: EIPWorker${Index}
          TTL: 300
          Type: A
        Type: AWS::Route53::RecordSet

  InstanceProfile:
    Properties:
      Roles: [!Ref Role]
    Type: AWS::IAM::InstanceProfile

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  KeyPair:
    Properties:
      KeyName: !Sub KeyPair-${AWS::StackName}
      PublicKeyMaterial: !Ref KeyPairPublicKeyMaterial
    Type: AWS::EC2::KeyPair

  Role:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          -
            Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    Type: AWS::IAM::Role

  RoutePublic:
    DependsOn: [VPCGatewayAttachment]
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref RouteTablePublic
    Type: AWS::EC2::Route

  RouteTablePublic:
    Properties:
      VpcId: !Ref VPC
    Type: AWS::EC2::RouteTable

  SecurityGroup:
    Properties:
      GroupDescription: Security Group to access via SSH the EC2 Instances
      SecurityGroupIngress: 
        - 
          CidrIp: !Ref SecurityGroupCidrIp
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22        
      VpcId: !Ref VPC
    Type: AWS::EC2::SecurityGroup

  SubnetPublic:
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: !Ref AWS::Region
      CidrBlock: !Ref SubnetCidrBlockPublic
      VpcId: !Ref VPC
    Type: AWS::EC2::Subnet

  SubnetRouteTableAssociationPublic:
    Properties:
      RouteTableId: !Ref RouteTablePublic
      SubnetId: !Ref SubnetPublic
    Type: AWS::EC2::SubnetRouteTableAssociation

  VPC:
    Properties:
      CidrBlock: !Ref VPCCidrBlock
    Type: AWS::EC2::VPC

  VPCGatewayAttachment:
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
    Type: AWS::EC2::VPCGatewayAttachment

Transform: AWS::LanguageExtensions
